name: lamatdating
description: Lamat Dating App Flutter project.
publish_to: "none"

version: 8.0.0+29

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  agora_rtc_engine:
  animations:
  async:
  audio_session:
  audioplayers:
  awesome_notifications:
  better_open_file:
  bouncing_widget:
  cached_network_image:
  camera:
  camera_web:
  carousel_slider:
  chewie:
  circular_countdown_timer:
  cloud_firestore:
  cloud_functions:
  collection:
  contacts_service:
  crypto:
  custom_pop_up_menu:
  dependency_validator:
  detectable_text_field:
  device_info_plus:
  devicelocale:
  easy_localization:
  emoji_picker_flutter:
  encrypt:
  expandable_text:
  extended_image:
  ffmpeg_kit_flutter_min_gpl:
  ffmpeg_wasm:
  file_picker:
  firebase_app_check:
  firebase_auth:
  firebase_core:
  import_sorter:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_branch_sdk:
  flutter_cache_manager:
  flutter_cached_pdfview:
  flutter_dotenv:
  flutter_downloader:
  flutter_easyloading:
  flutter_emoji:
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  flutter_image_compress:
  flutter_linkify:
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  intl_translation:
  flutter_native_splash:
  flutter_otp_text_field:
  flutter_paystack_plus:
  flutter_riverpod:
  flutter_secure_storage:
  flutter_sound:
  flutter_stripe:
  flutter_svg:
  flutter_video_info:
#  fluttertoast:
  font_awesome_flutter:
  fraction:
  gallery_saver:
  geolocator:
  giphy_get:
  google_fonts:
  google_mobile_ads:
  google_sign_in:
  google_translate:
  hive_flutter:
  holding_gesture:
  image:
  image_editor:
  image_editor_plus:
  image_picker:
  intl:
  jiffy:
  link_preview_generator:
  local_auth:
  localstorage:
  location:
  logger:
  lottie:
  marquee:
  media_info:
  mime:
  ntp:
  oktoast:
  overlay_support:
  package_info_plus:
  page_transition:
  path:
  path_provider:
  percent_indicator:
  permission_handler:
  photo_view:
  pip_view:
  purchases_flutter:
#  qr_code_scanner:
  qr_flutter:
  receive_sharing_intent:
  restart_app:
  rxdart:
  scoped_model:
  share_plus:
  shared_preferences:
  smooth_page_indicator:
  sms_autofill:
  social_media_recorder:
  stacked:
  swipe_cards:
  the_apple_sign_in:
  tuple:
  tutorial_coach_mark:
  universal_platform:
  url_launcher:
  video_compress:
  video_editor:
  video_player:
  video_thumbnail:
  visibility_detector:
  voice_message_package:
  vph_web_date_picker:
  wakelock_plus:
  websafe_svg:
  webview_flutter:
  file_saver:
  universal_html:
  webview_flutter_web:
  webview_flutter_platform_interface:
  flutter_html:
  gif_view:
  redacted:
  inner_glow:
  http:
  http_client_helper:
  dio:
  just_audio:
  in_app_purchase:
  flutter_stripe_web:
  uuid:
  flutter_nude_detector:
  audioplayers_darwin:
  document_selfie_verification:
  map_location_picker: ^1.3.1

dependency_overrides:
  screenshot: ^3.0.0
  photo_manager: ^3.2.3
  extended_image: ^8.2.1
  http_client_helper: ^3.0.0
  flutter_paypal:
    path: "flutter_paypal-0.2.0"
  http: ^1.2.2
  fading_edge_scrollview: ^4.1.1
  flutterwave_standard:
    path: "flutterwave_standard-1.0.8"
  wechat_assets_picker: ^9.2.0
  web: ^1.0.0
  permission_handler_html:
    git:
      url: https://github.com/hpoul/flutter-permission-handler.git
      path: permission_handler_html
      ref: permissiondescriptor

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/json/
    - assets/flags/
    - assets/json/lottie/
    - assets/
    - assets/icons/
    - assets/translations/
    - assets/images/common/
    - assets/ml_models/

  fonts:
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplayRegular.otf
        - asset: assets/fonts/SFUIDisplayMedium.otf
          weight: 500 # Medium weight is usually 500
        - asset: assets/fonts/SFUIDisplayBold.otf
          weight: 700 # Bold weight is usually 700
        - asset: assets/fonts/SFUIDisplaySemibold.otf
          weight: 600 # Semibold weight can be between 500 and 600, use 600 here
        - asset: assets/fonts/SFUIDisplayHeavy.otf
          weight: 800 # Heavy weight is usually 800
        - asset: assets/fonts/SFUIDisplayLight.otf
          weight: 300 # Light weight is usually 300
flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: true
  web: true

  background_image: "assets/images/backgroud.png"
  image: "assets/logos/symbol-wh.png"

  android_12:
    color: "#6E3DFF"
    image: assets/logos/logo-wh-tr.png
    image_dark: assets/logos/logo-wh-tr.png
